# Generated by Django 5.0.9 on 2026-10-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0002_sla_ticket_due_at_ticketcomment_ticketattachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tagi",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("summary", models.CharField(blank=True, max_length=512)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Szkic"),
                            ("PUBLISHED", "Opublikowany"),
                            ("ARCHIVED", "Zarchiwizowany"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kb_articles_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_articles",
                        to="tickets.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="articles", to="kb.articletag"),
                ),
            ],
            options={
                "verbose_name": "Artykuł",
                "verbose_name_plural": "Artykuły",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"], name="kb_knowledg_status_faff6d_idx"
                    ),
                    models.Index(fields=["category"], name="kb_knowledg_categor_536b5e_idx"),
                ],
            },
        ),
    ]
