# Generated by Django 5.0.9 on 2026-10-05 14:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0001_initial"),
        ("tickets", "0002_sla_ticket_due_at_ticketcomment_ticketattachment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgearticle",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(fields=["search_vector"], name="kb_search_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="kb_search_vector_gin"
            ),
        ),
    ]
