# Generated by Django 5.0.9 on 2026-10-05 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Niski"),
                            ("NORMAL", "Normalny"),
                            ("HIGH", "Wysoki"),
                            ("CRITICAL", "Krytyczny"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tickets.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(editable=False, max_length=32, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nowe"),
                            ("IN_PROGRESS", "W realizacji"),
                            ("WAITING", "Oczekuje"),
                            ("RESOLVED", "Rozwiązane"),
                            ("CLOSED", "Zamknięte"),
                        ],
                        default="NEW",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Niski"),
                            ("NORMAL", "Normalny"),
                            ("HIGH", "Wysoki"),
                            ("CRITICAL", "Krytyczny"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="tickets.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie",
                "verbose_name_plural": "Zgłoszenia",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "assigned_to"], name="tickets_tic_status_542056_idx"
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"], name="tickets_tic_created_80af85_idx"
                    ),
                    models.Index(fields=["-created_at"], name="tickets_tic_created_c2132d_idx"),
                ],
            },
        ),
    ]
