# Generated by Django 5.0.9 on 2026-10-05 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vendor", models.CharField(blank=True, max_length=128)),
                ("seats_total", models.PositiveIntegerField(default=1)),
                ("seats_used", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "key_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referencja do klucza (np. sejf, plik).",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Licencja",
                "verbose_name_plural": "Licencje",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="assets.assetcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria majątku",
                "verbose_name_plural": "Kategorie majątku",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("building", models.CharField(max_length=64)),
                ("floor", models.CharField(blank=True, max_length=16)),
                ("room", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "verbose_name": "Lokalizacja",
                "verbose_name_plural": "Lokalizacje",
                "ordering": ["building", "floor", "room"],
                "unique_together": {("building", "floor", "room")},
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Unikalny tag QR/kod inwentarzowy. Zostanie wygenerowany, jeśli pusty.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COMPUTER", "Komputer"),
                            ("LAPTOP", "Laptop"),
                            ("MONITOR", "Monitor"),
                            ("PRINTER", "Drukarka"),
                            ("PHONE", "Telefon"),
                            ("NETWORK", "Urządzenie sieciowe"),
                            ("OTHER", "Inne"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=128)),
                ("model_name", models.CharField(blank=True, max_length=128, verbose_name="Model")),
                ("serial_number", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_USE", "W użyciu"),
                            ("IN_STOCK", "W magazynie"),
                            ("REPAIR", "W naprawie"),
                            ("RETIRED", "Wycofany"),
                        ],
                        default="IN_STOCK",
                        max_length=16,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_until", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="assets.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zasób",
                "verbose_name_plural": "Zasoby",
                "ordering": ["tag"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_date", models.DateField(default=django.utils.timezone.now)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assets.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Przypisanie",
                "verbose_name_plural": "Przypisania",
                "ordering": ["-from_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["asset", "to_date"], name="assets_asse_asset_i_f836ca_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status", "type"], name="assets_asse_status_5afd5b_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["assigned_to"], name="assets_asse_assigne_8034d6_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["location"], name="assets_asse_locatio_8c1d63_idx"),
        ),
    ]
